name: Publish a Release Preview

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          dev: no
          php_version: "8.0"
      - run: |
          sudo apt-get install zip -y
          zip -r AntCMS.zip .
        working-directory: ./src
      - run: |
          npm install -D tailwindcss
          rm -f ./src/Themes/Default/Assets/Dist/tailwind.css
          npx tailwindcss -i ./src/Themes/Default/Assets/tailwind.css -o ./src/Themes/Default/Assets/Dist/tailwind.css --minify
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./src/AntCMS.zip"
          prerelease: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          name: "Preview Build"
          tag: "latest-preview"
          body: "A rolling preview release of AntCMS that is updated with each commit."
