name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: |
          cp ./tests/Includes/config.yaml ./src/config.yaml
      - uses: php-actions/phpunit@v3
        with: 
          php_version: "8.0"
          args: "tests"
