name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - run: |
          cp ./tests/Includes/Config.yaml ./src/Config/Config.yaml
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: src/Vendor/autoload.php
          php_version: ${{ matrix.php_version }}
          args: "tests"
          php_extensions: apcu
