name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - run: |
          cp ./tests/Includes/config.yaml ./src/Config/config.yaml
          sudo apt-get install tree
      - uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: src/Vendor/autoload.php
          php_version: "8.0"
          args: --coverage-text coverage.txt
          configuration: "phpunit.xml"
          php_extensions: xdebug
      - uses: codecov/codecov-action@v3
