name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          dev: yes
          php_version: ${{ matrix.php_version }}
          php_extensions: apcu

      - run: cp ./tests/Includes/Config.yaml ./src/Config/Config.yaml

      - run: php src/Vendor/bin/phpunit
